---
- name: Check images before installing Kubernetes service {{ k8s_service_name }}
  include_tasks:
    file: check-images.yml
    apply:
      tags: always
  vars:
    image_check_name: "{{ k8s_service_name }}"
    image_check_images: "{{ service_image_requirements.get(k8s_service_name, []) }}"
  when:
    - k8s_service_name not in ['common', 'containerd']
    - inventory_hostname == groups['master'][0]
    - (service_image_requirements.get(k8s_service_name, [])) | length > 0

- name: Run Kubernetes service role {{ k8s_service_name }}
  include_role:
    name: "{{ k8s_service_roles[k8s_service_name] }}"
    apply:
      tags: always
  tags: always
