---
- name: Check images before installing extra service {{ k8s_extra_service.name }}
  include_tasks:
    file: check-images.yml
    apply:
      tags: extra_services
  vars:
    image_check_name: "{{ k8s_extra_service.name }}"
    image_check_images: "{{ extra_service_image_requirements.get(k8s_extra_service.name, []) }}"
  when: (extra_service_image_requirements.get(k8s_extra_service.name, [])) | length > 0

- name: Run extra service role {{ k8s_extra_service.name }}
  include_role:
    name: "{{ k8s_extra_service.role }}"
    apply:
      tags: extra_services
  tags: extra_services
