apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: haproxy-exporter
  namespace: kube-system
  labels:
    app: haproxy-exporter
spec:
  selector:
    matchLabels:
      app: haproxy-exporter
  template:
    metadata:
      labels:
        app: haproxy-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: haproxy-exporter
          image: docker-registry:4000/vht/haproxy-exporter:v0.15.0
          imagePullPolicy: IfNotPresent
          args:
            - "--web.listen-address=:9101"
            - "--haproxy.scrape-uri=http://127.0.0.1:8404/;csv"
          ports:
            - containerPort: 9101
              hostPort: 9101
              name: metrics
              protocol: TCP
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
