---
- name: Render Multus manifest on bootstrap master
  template:
    src: multus-daemonset_v4.1.3.yaml.j2
    dest: "{{ __bootstrap_dir }}/multus-daemonset_v4.1.3.yaml"
  when:
    - "'multus' in k8s_install_services"
    - multi_network | bool
    - inventory_hostname == groups['master'][0]

- name: Apply Multus CNI
  shell: |
    set -Eeuo pipefail
    kubectl apply -f {{ __bootstrap_dir }}/multus-daemonset_v4.1.3.yaml
  args:
    executable: /bin/bash
  when:
    - "'multus' in k8s_install_services"
    - multi_network | bool
    - inventory_hostname == groups['master'][0]
