---
- name: Render metrics-server manifest on bootstrap master
  template:
    src: metric-server-v0.8.0.yaml.j2
    dest: "{{ __bootstrap_dir }}/metric-server-v0.8.0.yaml"
  when:
    - "'metrics_server' in k8s_install_services"
    - inventory_hostname == groups['master'][0]

- name: Apply metrics-server
  shell: |
    set -Eeuo pipefail
    kubectl apply -f {{ __bootstrap_dir }}/metric-server-v0.8.0.yaml
  args:
    executable: /bin/bash
  when:
    - "'metrics_server' in k8s_install_services"
    - inventory_hostname == groups['master'][0]
