apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ip-pool-exporter
  name: ip-pool-exporter
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ip-pool-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ip-pool-exporter
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - java -jar -Dserver.port=9998 -Droot.log.level=INFO prometheus-custom-exporter-1.0.3.jar
        image: docker-registry:4000/ip-pool-exporter:1.0.3
        imagePullPolicy: IfNotPresent
        name: ip-pool-exporter
        ports:
        - containerPort: 9998
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        workingDir: /u01/app/lib
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccount: prometheus-workload-reader
      serviceAccountName: prometheus-workload-reader
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: ip-pool-exporter
  namespace: kube-system
spec:
  ports:
  - nodePort: 9998
    port: 9998
    protocol: TCP
    targetPort: 9998
  selector:
    app: ip-pool-exporter
  sessionAffinity: None
  type: NodePort
