---
- name: set kubelet csr approver runtime facts
  set_fact:
    __bootstrap_dir: "{{ __bootstrap_dir | default('/root/kubebootstrap') }}"
    __registry_prefix: "{{ __registry_prefix | default(registry_name ~ ':' ~ registry_port) }}"

- name: create bootstrap directory for kubelet csr approver
  file:
    path: "{{ __bootstrap_dir }}"
    state: directory

- name: render kubelet csr approver manifest
  template:
    src: kubelet-csr-approver.yaml.j2
    dest: "{{ __bootstrap_dir }}/kubelet-csr-approver.yaml"

- name: apply kubelet csr approver
  shell: |
    kubectl apply -f {{ __bootstrap_dir }}/kubelet-csr-approver.yaml
  register: __kubelet_csr_approver_apply

- tags: ["debug"]
  debug:
    var: __kubelet_csr_approver_apply.stdout_lines
