---
- name: print join node command
  register: __join_command
  shell: kubeadm token create --print-join-command

- name: re-upload key
  register: __cert_key
  shell: kubeadm init phase upload-certs --upload-certs

- name: join control plane
  set_fact:
    control_join: |
      {{ __join_command.stdout }} --control-plane --certificate-key {{ __cert_key.stdout_lines[2] }}
    worker_join: |
      {{ __join_command.stdout }}

- tags: ["debug"]
  debug:
    msg: |
      {{ control_join }}
      {{ worker_join }}

- name: regen script for used later
  shell: |
    cat > /root/regen_join_command.sh <<'EOF'
    ISC=$(kubectl get node $(echo $(hostname) | tr '[:upper:]' '[:lower:]') --show-labels | grep control-plane)
    if [[ -z "$ISC" ]]; then
          echo must run on a control/master node. Cannot run in a normal client.
          exit 1
    fi
    WJOIN=$(kubeadm token create --print-join-command)
    CERT_UPLOAD=$(kubeadm init phase upload-certs --upload-certs | awk 'NR==3')
    CJOIN="$WJOIN --control-plane --certificate-key $CERT_UPLOAD --apiserver-advertise-address $(cat /etc/sysconfig/kubeip)"
    cat <<EOM
    - Worker join command: 
      $WJOIN
    - Control join command: 
      $CJOIN
    EOM
    EOF
