---
# tasks file for roles/kubernetes-optimized
- include_tasks: setup.yml
- include_tasks: bootstrap.yml
  when: "'node_bootstrap' in k8s_install_services"
  tags: node_bootstrap
- name: bootstrap cluster tasks
  when: >
    inventory_hostname == groups['master'][0]
    and 'control_plane' in k8s_install_services
  tags: control_plane
  block:
    - include_tasks: audit.yml
    - name: generate kubernetes install files
      loop: "{{ list_init_files }}"
      template:
        src: "{{ item }}"
        dest: "/root/kubebootstrap/{{ item | replace('.j2','') }}"
    - include_tasks: image_pullable.yml
    - name: init cluster
      register: __init_cluster
      shell: |
        cat > /root/init-k8s.sh <<'EOF'
        KUBEADMF=/root/kubeadm.yaml
        kubeadm config migrate --old-config {{ __bootstrap_dir }}/kubeadm-config.yaml --new-config $KUBEADMF
        sed -i 's/controlPlaneComponentHealthCheck.*/controlPlaneComponentHealthCheck: 30s/g' $KUBEADMF 
        echo '---' >> $KUBEADMF
        awk '/apiVersion: kubelet.config.k8s.io\/v1beta1/{flag=1} flag && /^---/ {exit} flag' {{ __bootstrap_dir }}/kubeadm-config.yaml >> $KUBEADMF
        echo '---' >> $KUBEADMF
        awk '/apiVersion: kubeproxy.config.k8s.io\/v1alpha1/{flag=1} flag && /^---/ {exit} flag' {{ __bootstrap_dir }}/kubeadm-config.yaml >> $KUBEADMF
        kubeadm init --upload-certs --config $KUBEADMF
        EOF
        bash /root/init-k8s.sh | tee {{ __bootstrap_dir }}/logs/init-cluster.{{ __session_time }}.log
    - tags: ["debug"]
      debug:
        var: __init_cluster.stdout_lines
    - include_tasks: join_command.yml
- include_tasks: config_kube.yml
  when: >
    inventory_hostname == groups['master'][0]
    and 'kubeconfig' in k8s_install_services
  tags: kubeconfig
- include_tasks: install_cni.yml
  when: >
    inventory_hostname == groups['master'][0]
    and 'cni' in k8s_install_services
  tags: cni
- include_tasks: join_command.yml
  when: >
    inventory_hostname == groups['master'][0]
    and 'join_nodes' in k8s_install_services
    and 'control_plane' not in k8s_install_services
  tags: join_nodes
- name: join nodes to cluster
  when: >
    inventory_hostname != groups['master'][0]
    and 'join_nodes' in k8s_install_services
  tags: join_nodes
  shell: |
    cat > /root/join-cluster.sh <<'EOF'
    if [[ -f /etc/kube-master-metadata ]]; then
      {{ hostvars[groups['master'][0]].control_join }} --apiserver-advertise-address {{ k8s_ip }}
    else
      {{ hostvars[groups['master'][0]].worker_join }}
    fi
    EOF
    bash /root/join-cluster.sh | tee {{ __bootstrap_dir }}/logs/join-cluster.{{ __session_time }}.log
- name: non-bootstrap master post-deploy
  when: >
    'master' in group_names 
    and inventory_hostname != groups['master'][0]
    and 'kubeconfig' in k8s_install_services
  tags: kubeconfig
  block:
    - include_tasks: audit.yml
    - include_tasks: config_kube.yml
- include_tasks: post.yml
  when: >
    inventory_hostname == groups['master'][0]
    and 'addons' in k8s_install_services
  tags: addons
- include_tasks: patch.yml
  when: >
    inventory_hostname in groups['master']
    and 'static_pod_patch' in k8s_install_services
  tags:
    - patch
    - static_pod_patch
