[MULTILINE_PARSER]
    Name          mysql_slow_multiline
    Type          regex
    Flush_Timeout 5000

    Rule      start_state   "^# Time:"        cont
    Rule      cont          "^(?!# Time:)"    cont
