---
- name: build add-on manifest file list
  set_fact:
    __addon_manifest_files: "{{ etcd_operation + ((add_on_self | list) if add_on_self is defined else []) }}"
  when:
    - inventory_hostname == groups['master'][0]
    - "'addons' in k8s_install_services"

- name: generate add-on manifests
  loop: "{{ __addon_manifest_files }}"
  template:
    src: "{{ item }}"
    dest: "/root/kubebootstrap/{{ item | replace('.j2','') }}"
  when:
    - inventory_hostname == groups['master'][0]
    - "'addons' in k8s_install_services"

- name: create etcd backup/rotate/defrag cronjob, install metric server
  shell: |
      cat > /root/post-deploy.sh <<'EOF'
      kubectl apply \
        -f {{ __bootstrap_dir }}/etcd-backup-rotate-cronjob.yaml \
        -f {{ __bootstrap_dir }}/etcd-defrag.yaml \
        -f {{ __bootstrap_dir }}/metric-server-v0.8.0.yaml \
        -f {{ __bootstrap_dir }}/kube-state-metrics.yaml
      EOF
      bash /root/post-deploy.sh | tee {{ __bootstrap_dir }}/logs/post-deploy.{{ __session_time }}.log
  when:
    - inventory_hostname == groups['master'][0]
    - "'addons' in k8s_install_services"
