---
- name: Render HAProxy and Keepalived bootstrap script
  tags: ["dryrun"]
  template:
    src: k8s-ha-bootstrap.sh.j2
    dest: /root/kube-ha-bootstrap.sh
    mode: '0755'
  when:
    - "'k8s_ha' in k8s_install_services"
    - "'master' in group_names"

- name: Run HAProxy and Keepalived bootstrap script
  shell: |
    set -Eeuo pipefail
    bash /root/kube-ha-bootstrap.sh | tee {{ __bootstrap_dir }}/logs/k8s-ha-bootstrap.{{ __session_time }}.log
  args:
    executable: /bin/bash
  when:
    - "'k8s_ha' in k8s_install_services"
    - "'master' in group_names"
