[HARBOR]
harbor01 ansible_host=172.20.3.117 ansible_user=root ansible_password='123456a@'
harbor02 ansible_host=172.20.3.126 ansible_user=root ansible_password='123456a@'
harbor03 ansible_host=172.20.3.57 ansible_user=root ansible_password='123456a@'
