---
- name: Render Whereabouts manifests on bootstrap master
  loop: "{{ whereabouts_init }}"
  template:
    src: "{{ item }}"
    dest: "{{ __bootstrap_dir }}/{{ item | replace('.j2','') }}"
  when:
    - "'whereabouts' in k8s_install_services"
    - multi_network | bool
    - inventory_hostname == groups['master'][0]

- name: Apply Whereabouts IPAM
  shell: |
    set -Eeuo pipefail
    kubectl apply \
      -f {{ __bootstrap_dir }}/whereabouts_ippools.yaml \
      -f {{ __bootstrap_dir }}/whereabouts_ippools-cleaner.yaml \
      -f {{ __bootstrap_dir }}/whereabouts_daemonset_install.yaml
  args:
    executable: /bin/bash
  when:
    - "'whereabouts' in k8s_install_services"
    - multi_network | bool
    - inventory_hostname == groups['master'][0]
