---
- name: Install HAProxy exporter package on master nodes
  package:
    name: "{{ haproxy_exporter.package_name }}"
    state: present
  when:
    - "'haproxy_exporter' in k8s_install_services"
    - "'master' in group_names"

- name: Install HAProxy exporter systemd unit on master nodes
  template:
    src: haproxy-exporter.service.j2
    dest: /etc/systemd/system/haproxy-exporter.service
    mode: '0644'
  when:
    - "'haproxy_exporter' in k8s_install_services"
    - "'master' in group_names"

- name: Start HAProxy exporter host service on master nodes
  systemd:
    name: haproxy-exporter
    state: restarted
    enabled: true
    daemon_reload: true
  when:
    - "'haproxy_exporter' in k8s_install_services"
    - "'master' in group_names"
