---
- name: generate containerd config file
  tags: ["dryrun"]
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
  when: "'containerd' in k8s_install_services"

- name: generate containerd bootstrap script
  tags: ["dryrun"]
  template:
    src: containerd-bootstrap.sh.j2
    dest: /root/kube-containerd-bootstrap.sh
    mode: '0755'
  when: "'containerd' in k8s_install_services"

- name: execute containerd bootstrap script
  shell: bash /root/kube-containerd-bootstrap.sh | tee {{ __bootstrap_dir }}/logs/containerd-bootstrap.{{ __session_time }}.log
  when: "'containerd' in k8s_install_services"
