---
- name: Render etcd operation job manifests on bootstrap master
  loop: "{{ etcd_operation }}"
  template:
    src: "{{ item }}"
    dest: "{{ __bootstrap_dir }}/{{ item | replace('.j2','') }}"
  when:
    - "'etcd_jobs' in k8s_install_services"
    - inventory_hostname == groups['master'][0]

- name: Apply etcd operation jobs
  shell: |
    set -Eeuo pipefail
    kubectl apply \
      -f {{ __bootstrap_dir }}/etcd-backup-rotate-cronjob.yaml \
      -f {{ __bootstrap_dir }}/etcd-defrag.yaml
  args:
    executable: /bin/bash
  when:
    - "'etcd_jobs' in k8s_install_services"
    - inventory_hostname == groups['master'][0]
