# Inventory file

[master]
172.20.3.117 ansible_ssh_user=root ansible_ssh_pass=123456a@ k8s_ip=172.20.3.117 priority=5
172.20.3.126 ansible_ssh_user=root ansible_ssh_pass=123456a@ k8s_ip=172.20.3.126 priority=4
172.20.3.57 ansible_ssh_user=root ansible_ssh_pass=123456a@ k8s_ip=172.20.3.57 priority=3

[worker]
