---
etcd_requests_cpu: "100m"
etcd_requests_memory: "128Mi"
etcd_limits_cpu: "2"
etcd_limits_memory: "4Gi"
apiserver_requests_cpu: "100m"
apiserver_requests_memory: "128Mi"
apiserver_limits_cpu: "2"
apiserver_limits_memory: "4Gi"
controller_manager_requests_cpu: "100m"
controller_manager_requests_memory: "128Mi"
controller_manager_limits_cpu: "2"
controller_manager_limits_memory: "4Gi"
scheduler_requests_cpu: "100m"
scheduler_requests_memory: "128Mi"
scheduler_limits_cpu: "2"
scheduler_limits_memory: "4Gi"
