---
- name: Distribute admin kubeconfig to configured master users
  loop: "{{ master_user }}"
  loop_control:
    loop_var: kubeconfig_user
  ignore_errors: true
  shell: |
    set -Eeuo pipefail
    if ! id -u {{ kubeconfig_user }} >/dev/null 2>&1; then
      echo user {{ kubeconfig_user }} does not exist > {{ __bootstrap_dir }}/logs/config-kube.{{ __session_time }}.log
    else
      MYHOME=$(getent passwd {{ kubeconfig_user }} | cut -d: -f6)
      install -d -m 0700 -o {{ kubeconfig_user }} -g {{ kubeconfig_user }} $MYHOME/.kube
      install -m 0600 -o {{ kubeconfig_user }} -g {{ kubeconfig_user }} /etc/kubernetes/admin.conf $MYHOME/.kube/config
    fi
  args:
    executable: /bin/bash
  when:
    - "'kubeadm' in k8s_install_services"
    - "'master' in group_names"
