---
- name: Run kubeadm preparation tasks
  include_tasks: prepare.yml
  when: "'kubeadm' in k8s_install_services"

- name: Run kubeadm control-plane initialization tasks
  include_tasks: init.yml
  when: "'kubeadm' in k8s_install_services"

- name: Join additional Kubernetes nodes
  include_tasks: join.yml
  when: "'kubeadm' in k8s_install_services"

- name: Configure kubeconfig for master users
  include_tasks: kubeconfig.yml
  when: "'kubeadm' in k8s_install_services"
