---
- name: Render cert-exporter manifest on bootstrap master
  template:
    src: cert-exporter.yaml.j2
    dest: "{{ __bootstrap_dir }}/cert-exporter.yaml"
  when:
    - "'cert_exporter' in k8s_install_services"
    - inventory_hostname == groups['master'][0]

- name: Apply cert-exporter
  shell: |
    set -Eeuo pipefail
    kubectl apply -f {{ __bootstrap_dir }}/cert-exporter.yaml
  args:
    executable: /bin/bash
  when:
    - "'cert_exporter' in k8s_install_services"
    - inventory_hostname == groups['master'][0]
